# Generated by Django 5.1.1 on 2025-08-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomepayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Valyuta kursi'),
        ),
        migrations.AlterField(
            model_name='incomepayment',
            name='payment_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paymentpurpose', verbose_name='To`lov maqsadi'),
        ),
    ]
