# Generated by Django 5.1.1 on 2024-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('model_sign_date', models.DateTimeField()),
                ('model_FI_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('example_LD', models.CharField(max_length=100)),
                ('example_FIT', models.CharField(max_length=100)),
                ('example_BULK', models.CharField(max_length=100)),
                ('example_Print', models.CharField(max_length=100)),
                ('example_PPS', models.CharField(max_length=100)),
                ('slice_qty', models.IntegerField()),
                ('slice_status', models.CharField(max_length=50)),
                ('print_qty', models.IntegerField()),
                ('print_status', models.CharField(max_length=50)),
                ('sewing_qty', models.IntegerField()),
                ('sewing_status', models.CharField(max_length=50)),
                ('packing_qty', models.IntegerField()),
                ('packing_status', models.CharField(max_length=50)),
                ('date_of_update', models.CharField(max_length=50)),
            ],
        ),
    ]
