# Generated by Django 5.1.1 on 2024-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='family_situation',
            field=models.CharField(blank=True, choices=[('Yolg`iz', 'Yolg`iz'), ('Oilali', 'Oilali')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='sex',
            field=models.CharField(blank=True, choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
