# Generated by Django 5.1.1 on 2025-08-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_incomepayment_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomepayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valyuta kursi'),
        ),
    ]
