# Generated by Django 5.1.1 on 2025-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_incomepayment_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomepayment',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m'), ('USD', 'Dollar'), ('EUR', 'Yevro'), ('RUB', 'Rubl')], default='UZS', max_length=10, verbose_name='Pul birligi'),
        ),
    ]
