# Generated by Django 5.1.1 on 2024-09-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='avatar',
            field=models.ImageField(blank=True, default='default.avatar.jpg', null=True, upload_to='media/avatars/'),
        ),
    ]
