# Generated by Django 5.1.1 on 2024-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_record_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
