# Generated by Django 5.1.1 on 2024-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_record_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.jpg', upload_to='avatars/'),
        ),
    ]
