# Generated by Django 5.1.1 on 2024-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_record_created_by_record_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_source', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_office', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_communication', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS'), ('social', 'Social Media')], default='email', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_status', models.CharField(choices=[('new', 'New Lead'), ('qualified', 'Qualified'), ('customer', 'Customer'), ('inactive', 'Inactive')], default='new', max_length=50)),
                ('account_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(blank=True, null=True)),
                ('opt_in_status', models.BooleanField(default=False)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
