# Generated by Django 5.1.1 on 2024-10-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contact_created_at_contact_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('can_view_contact', 'Can view contact details')]},
        ),
    ]
