# Generated by Django 5.1.1 on 2024-10-18 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_contact_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('education', 'Education'), ('ecommerce', 'Ecommerce'), ('other', 'Other')], max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='accounts', to='website.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
