# Generated by Django 5.1.1 on 2024-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contract_expiry',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='engagement_score',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='opt_in_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(choices=[('textile_manufacturing', 'Textile Manufacturing'), ('apparel_fashion', 'Apparel and Fashion'), ('home_textiles', 'Home Textiles'), ('industrial_textiles', 'Industrial Textiles'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('ecommerce', 'E-commerce'), ('furniture', 'Furniture'), ('interior_design', 'Interior Design'), ('hospitality', 'Hospitality'), ('healthcare', 'Healthcare'), ('automotive', 'Automotive'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('sports_leisure', 'Sports and Leisure'), ('government', 'Government/Public Sector'), ('education', 'Education'), ('non_profit', 'Non-profit/NGO'), ('other', 'Other')], default='textile_manufacturing', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('email_campaign', 'Email Campaign'), ('social_media', 'Social Media'), ('trade_show', 'Trade Show'), ('direct_call', 'Direct Call'), ('partner', 'Partner'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_status',
            field=models.CharField(choices=[('new_inquiry', 'New Inquiry'), ('initial_contact', 'Initial Contact Made'), ('sample_requested', 'Sample Requested'), ('sample_sent', 'Sample Sent'), ('quote_requested', 'Quotation Requested'), ('quote_sent', 'Quotation Sent'), ('negotiation', 'Negotiation/Follow-Up'), ('awaiting_po', 'Awaiting Purchase Order'), ('po_received', 'Purchase Order Received'), ('production_started', 'Production Started'), ('order_shipped', 'Order Shipped'), ('deal_closed', 'Deal Closed'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new_inquiry', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_communication',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('video_call', 'Video Call (Zoom/Google Meet)'), ('in_person', 'In-Person Meeting'), ('linkedin', 'LinkedIn Messaging'), ('fax', 'Fax')], default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Inquiry'), ('trade_show', 'Trade Shows/Exhibitions'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaigns'), ('cold_call', 'Cold Call/Direct Outreach'), ('distributor', 'Distributor/Agent'), ('online_marketplace', 'Online Marketplace'), ('print_media', 'Print Media'), ('word_of_mouth', 'Word of Mouth'), ('previous_client', 'Previous Client'), ('local_business', 'Local Business Network'), ('partnership', 'Partnerships'), ('phone_inquiry', 'Inbound Phone Inquiry'), ('search_engine', 'Search Engine')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new_inquiry', 'New Inquiry'), ('initial_contact', 'Initial Contact Made'), ('sample_requested', 'Sample Requested'), ('sample_sent', 'Sample Sent'), ('quote_requested', 'Quotation Requested'), ('quote_sent', 'Quotation Sent'), ('negotiation', 'Negotiation/Follow-Up'), ('awaiting_po', 'Awaiting Purchase Order'), ('po_received', 'Purchase Order Received'), ('production_started', 'Production Started'), ('order_shipped', 'Order Shipped'), ('deal_closed', 'Deal Closed'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=20),
        ),
    ]
