# Generated by Django 5.1.1 on 2024-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_contact_last_name_alter_contact_phone_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('UZ', 'Uzbekistan'), ('RU', 'Russia'), ('CN', 'China'), ('TR', 'Turkey'), ('US', 'United States'), ('DE', 'Germany'), ('IN', 'India'), ('IT', 'Italy'), ('JP', 'Japan'), ('FR', 'France'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('BR', 'Brazil'), ('AU', 'Australia'), ('KR', 'South Korea'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('MX', 'Mexico'), ('CH', 'Switzerland'), ('PL', 'Poland'), ('NG', 'Nigeria'), ('ID', 'Indonesia'), ('ZA', 'South Africa'), ('AR', 'Argentina'), ('EG', 'Egypt'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('VN', 'Vietnam'), ('TH', 'Thailand'), ('BD', 'Bangladesh'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('KZ', 'Kazakhstan'), ('UA', 'Ukraine'), ('PK', 'Pakistan'), ('IL', 'Israel'), ('GR', 'Greece'), ('PT', 'Portugal'), ('BE', 'Belgium'), ('DK', 'Denmark'), ('NO', 'Norway'), ('FI', 'Finland'), ('AT', 'Austria'), ('HU', 'Hungary'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('NZ', 'New Zealand'), ('CL', 'Chile'), ('PE', 'Peru'), ('CO', 'Colombia'), ('OTHER', 'Other')], default='UZ', max_length=5),
        ),
    ]
