# Generated by Django 5.1.1 on 2024-10-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_contact_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time_zone',
        ),
    ]
