# Generated by Django 5.1.1 on 2024-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_contact_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Website Inquiry'), ('trade_show', 'Trade Shows/Exhibitions'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaigns'), ('cold_call', 'Cold Call/Direct Outreach'), ('distributor', 'Distributor/Agent'), ('online_marketplace', 'Online Marketplace'), ('print_media', 'Print Media'), ('word_of_mouth', 'Word of Mouth'), ('previous_client', 'Previous Client'), ('local_business', 'Local Business Network'), ('partnership', 'Partnerships'), ('phone_inquiry', 'Inbound Phone Inquiry'), ('search_engine', 'Search Engine')], default='website', max_length=20),
        ),
    ]
