# Generated by Django 5.1.1 on 2024-10-23 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_contact_lead_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deal_status', models.CharField(choices=[('open', 'Open'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='open', max_length=10)),
                ('deal_stage', models.CharField(choices=[('initial_contact', 'Initial Contact'), ('sample_delivery', 'Sample Delivery'), ('quotation_sent', 'Quotation Sent'), ('negotiation', 'Negotiation'), ('final_approval', 'Final Approval'), ('order_processing', 'Order Processing'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='initial_contact', max_length=20)),
                ('deal_type', models.CharField(choices=[('not_selected', 'Not selected'), ('sale', 'Sale'), ('sale_of_fiber', 'Sale of Fiber'), ('sale_of_fabric', 'Sale of Fabric'), ('sale_of_yarn', 'Sale of Yarn'), ('sale_of_garment', 'Sale of Garment'), ('sale_of_services', 'Sale of Services')], default='not_selected', max_length=20)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('website_inquiry', 'Website Inquiry'), ('trade_show', 'Trade Show'), ('online_advertisement', 'Online Advertisement'), ('distributor', 'Distributor'), ('social_media', 'Social Media'), ('direct_visit', 'Direct Visit')], default='website_inquiry', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'Dollar ($)'), ('RUB', 'Ruble (₽)'), ('EUR', 'Euro (€)'), ('UZS', 'UZS (so‘m)')], default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('close_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='website.account')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='website.contact')),
            ],
        ),
    ]
