# Generated by Django 5.1.1 on 2024-10-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_deal_amount_alter_deal_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
