# Generated by Django 5.1.1 on 2024-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Product', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('not_selected', 'Not selected'), ('fiber', 'Fiber'), ('fabric', 'Fabric'), ('yarn', 'Yarn'), ('garment', 'Garment'), ('service', 'Service')], default='not_selected', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'Dollar ($)'), ('RUB', 'Ruble (₽)'), ('EUR', 'Euro (€)'), ('UZS', 'UZS (so‘m)')], default='USD', max_length=3)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
