# Generated by Django 5.1.1 on 2024-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
