# Generated by Django 5.1.1 on 2025-06-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_deal_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_status',
            field=models.CharField(choices=[('new_request', 'New Request'), ('initial_contact', 'Initial Contact Made'), ('sample_requested', 'Sample Requested'), ('sample_sent', 'Sample Sent'), ('quote_requested', 'Quotation Requested'), ('quote_sent', 'Quotation Sent'), ('negotiation', 'Negotiation/Follow-Up'), ('awaiting_po', 'Awaiting Purchase Order'), ('po_received', 'Purchase Order Received'), ('production_started', 'Production Started'), ('order_shipped', 'Order Shipped'), ('deal_closed', 'Deal Closed'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new_inquiry', max_length=50),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='requisition_images/')),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(blank=True, max_length=255)),
                ('usage_location', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('tonna', 'Tonna'), ('l', 'Litr (l)'), ('ml', 'Millilitr (ml)'), ('dona', 'Dona'), ('karopka', 'Karopka'), ('metr', 'Metr'), ('sm', 'Santimetr'), ('rulon', 'Rulon'), ('set', 'To‘plam (Set)'), ('pachka', 'Pachka'), ('quti', 'Quti'), ('juft', 'Juft'), ('list', 'List'), ('bo‘lak', 'Bo‘lak')], default='dona', help_text='O‘lchov birligini tanlang', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('previous_price', models.TextField(blank=True, help_text='Avvalgi xarid narxi va u bilan bog‘liq manba yoki joy haqida ma’lumot')),
                ('offer_prices1', models.TextField(blank=True, help_text='Yangi taklif narxlari, ularning manbalari yoki joylari haqida ma’lumot')),
                ('offer_prices2', models.TextField(blank=True, help_text='Yangi taklif narxlari, ularning manbalari yoki joylari haqida ma’lumot')),
                ('other_offers', models.TextField(blank=True, help_text="Qo'shimcha takliflar bo‘lsa, bu yerga yozing.")),
                ('is_delivered', models.BooleanField(default=False)),
                ('transferred_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('director_approved', models.BooleanField(default=False)),
                ('leader_approved', models.BooleanField(default=False)),
                ('finance_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('director_approved', 'Director Approved'), ('prices_added', 'Prices Added'), ('leader_approved', 'Leader Approved'), ('finance_approved', 'Finance Approved'), ('purchased', 'Purchased'), ('delivered', 'Delivered to Warehouse')], default='draft', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
