# Generated by Django 5.1.1 on 2025-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_contact_lead_status_requisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='director_approved',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='finance_approved',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='leader_approved',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='status',
        ),
        migrations.AddField(
            model_name='requisition',
            name='deputy_director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='director_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('rad_etildi', 'Rad etildi')], default='kutishda', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='finance_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('bekor_qilindi', 'Bekor qilindi')], default='kutishda', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='leader_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('rad_etildi', 'Rad etildi')], default='kutishda', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='supply_manager_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='supply_status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('tugallandi', 'To‘liq bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='jarayonda', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='warehouse_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='warehouse_status',
            field=models.CharField(choices=[('yetib_kelmagan', 'Yetib kelmagan'), ('qabul_qilindi', 'Qabul qilindi')], default='yetib_keldi', max_length=20),
        ),
    ]
