# Generated by Django 5.1.1 on 2025-08-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_requisition_director_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='usage_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='director_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('rad_etildi', 'Rad etildi')], default='tasdiqlashda', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='finance_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('bekor_qilindi', 'Bekor qilindi')], default='tasdiqlashda', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='leader_status',
            field=models.CharField(choices=[('tasdiqlashda', 'Tasdiqlash jarayonida'), ('tasdiqlandi', 'Tasdiqlandi'), ('kutishda', 'Kutishda'), ('rad_etildi', 'Rad etildi')], default='tasdiqlashda', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='usage_location',
            field=models.CharField(choices=[('koson_fashion', 'Koson Fashion MCHJ'), ('bunyodkor', 'Bunyodkor MCHJ'), ('texnopark', 'Bunyodkor Industrial Texnopark')], default='bunyodkor', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='warehouse_status',
            field=models.CharField(choices=[('yetib_kelmagan', 'Yetib kelmagan'), ('qabul_qilindi', 'Qabul qilindi')], default='yetib_kelmagan', max_length=20),
        ),
    ]
