# Generated by Django 5.1.1 on 2025-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_requisition_usage_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='is_delivered',
        ),
    ]
