# Generated by Django 5.1.1 on 2025-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_remove_requisition_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='warehouse_status',
            field=models.CharField(blank=True, choices=[('yetib_kelmagan', 'Yetib kelmagan'), ('qabul_qilindi', 'Qabul qilindi')], default='yetib_kelmagan', max_length=20, null=True),
        ),
    ]
