# Generated by Django 5.1.1 on 2025-08-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_requisition_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='IncomePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Pul kelgan sana')),
                ('company_name', models.CharField(max_length=255, verbose_name='Korxona nomi')),
                ('inn', models.CharField(max_length=20, verbose_name='INN')),
                ('currency', models.CharField(choices=[('UZS', 'So‘m'), ('USD', 'Dollar'), ('EUR', 'Yevro'), ('RUB', 'Rubl')], max_length=10, verbose_name='Pul birligi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summasi')),
                ('payment_purpose', models.TextField(verbose_name='To‘lov maqsadi')),
                ('bank_payment_purpose', models.CharField(max_length=255, verbose_name='Bank to‘lov maqsadi')),
                ('account_number', models.CharField(max_length=50, verbose_name='Hisob raqami')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valyuta kursi')),
                ('amount_in_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='So‘mdagi qiymati')),
                ('our_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branch', verbose_name='Filial')),
            ],
        ),
    ]
