# Generated by Django 5.1.1 on 2025-08-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_branch_incomepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomepayment',
            name='bank_payment_purpose',
            field=models.TextField(verbose_name='Bank to‘lov maqsadi'),
        ),
        migrations.AlterField(
            model_name='incomepayment',
            name='payment_purpose',
            field=models.CharField(max_length=255, verbose_name='To‘lov maqsadi'),
        ),
    ]
