# Generated by Django 5.1.1 on 2025-08-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_incomepayment_bank_payment_purpose_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomePayment',
        ),
    ]
