# Generated by Django 5.1.1 on 2025-10-26 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Patok nomi')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ish turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (so‘m/dona)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_production', 'Ishlab chiqarishda'), ('paused', 'To‘xtatilgan'), ('completed', 'Bajarilgan'), ('canceled', 'Bekor qilingan'), ('shipped', 'Yuborilgan')], default='new', max_length=20, verbose_name='Holati')),
                ('client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz nomi')),
                ('artikul', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artikuli')),
                ('rangi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rangi')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Yuklanish vaqti')),
                ('model_picture', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Model rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Ironing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('daily_work_date', models.DateField(verbose_name='Kunlik dazmol ish sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ironing', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='FabricArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=200, verbose_name='Mato nomi')),
                ('measure_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdori')),
                ('measure_unit', models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('m', 'Metr')], default='kg', max_length=10, null=True, verbose_name='O‘lchov birligi')),
                ('gramaj', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gramaj')),
                ('arrival_date', models.DateTimeField(verbose_name='Qachon kelganligi')),
                ('factory_name', models.CharField(max_length=200, verbose_name='Qaysi fabrikadan kelganligi')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_arrival', to='plm.order', verbose_name='Qaysi buyurtma uchun')),
            ],
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastal_soni', models.PositiveIntegerField(verbose_name='Pastal soni')),
                ('pastal_olchami', models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('42-44', '42-44'), ('46-48', '46-48'), ('50-52', '50-52'), ('54-56', '54-56'), ('58-60', '58-60'), ('62-64', '62-64'), ('66-68', '66-68'), ('70-72', '70-72')], default='oversize', max_length=20, verbose_name='Pastal o‘lchami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuttings', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Aksessuar nomi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soni')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('metr', 'Metr'), ('pachka', 'Pachka'), ('paket', 'Paket'), ('quti', 'Quti'), ('litr', 'Litr')], default='dona', max_length=20, verbose_name='Birligi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('size', models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('42-44', '42-44'), ('46-48', '46-48'), ('50-52', '50-52'), ('54-56', '54-56'), ('58-60', '58-60'), ('62-64', '62-64'), ('66-68', '66-68'), ('70-72', '70-72')], default='oversize', max_length=20, verbose_name='O‘lchami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersize', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_quantity', models.PositiveIntegerField(default=0, verbose_name='Sifatli (o‘tgan) soni')),
                ('failed_quantity', models.PositiveIntegerField(default=0, verbose_name='Brak soni')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='Inspeksiya sanasi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='plm.order', verbose_name='Buyurtma')),
                ('ordersize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='plm.ordersize', verbose_name='Buyurtma o‘lchami')),
            ],
            options={
                'verbose_name': 'Sifat nazorati',
                'verbose_name_plural': 'Sifat nazoratlari',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sort', models.PositiveIntegerField(default=0, verbose_name='1-sort (sifatli)')),
                ('second_sort', models.PositiveIntegerField(default=0, verbose_name='2-sort')),
                ('defect', models.PositiveIntegerField(default=0, verbose_name='Brak (nuqsonli)')),
                ('classified_date', models.DateField(verbose_name='Tasnif sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='plm.order', verbose_name='Buyurtma')),
                ('ordersize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='plm.ordersize', verbose_name='Buyurtma o‘lchami (razmer)')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ['-classified_date'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(choices=[('karopka', 'Karopka'), ('paket', 'Paket'), ('xalta', 'Xalta')], default='karopka', max_length=20, verbose_name='Qadoq turi')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Qadoqlangan mahsulot soni')),
                ('box_quantity', models.PositiveIntegerField(verbose_name='Yopilgan karopkalar soni')),
                ('packed_date', models.DateField(verbose_name='Qadoqlangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='plm.order')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
                'ordering': ['-packed_date'],
            },
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('daily_work_date', models.DateField(verbose_name='Kunlik bosilgan pechat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_norm', models.PositiveIntegerField(verbose_name='Kunlik norma (dona)')),
                ('hourly_norm', models.PositiveIntegerField(verbose_name='Soatlik norma (dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.order', verbose_name='Buyurtma (Artikul)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism familiya')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plm.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artikul')),
                ('mijoz', models.CharField(max_length=200, verbose_name='Mijoz')),
                ('ish_soni', models.PositiveIntegerField(default=0, verbose_name='Ish soni')),
                ('bajarilgan', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bajarilgan')),
                ('kesim', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kesim soni')),
                ('dazmol', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dazmol soni')),
                ('pechat', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pechat soni')),
                ('sifat_nazorati', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sifat nazorati soni')),
                ('tasnif', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tasnif soni')),
                ('qadoq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qadoq soni')),
                ('tikim', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tikim soni')),
                ('model_picture', models.ImageField(blank=True, null=True, upload_to='models/', verbose_name='Model rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(verbose_name='Yuk chiqarish sanasi')),
                ('destination', models.CharField(max_length=200, verbose_name='Manzil')),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mashina raqami')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Haydovchi ismi')),
                ('package_type', models.CharField(choices=[('box', 'Karopka'), ('bag', 'Xalta'), ('packet', 'Paket'), ('pallet', 'Pallet'), ('other', 'Boshqa')], default='box', max_length=20, verbose_name='Qadoq turi')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='Yuk miqdori (dona)')),
                ('box_quantity', models.PositiveIntegerField(default=0, verbose_name='Karopkalar soni')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Yuklashga tayyor'), ('shipped', 'Yuklab jo‘natildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='shipments/files/', verbose_name='Biriktirilgan fayl (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='plm.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Yuklama',
                'verbose_name_plural': 'Yuklamalar',
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Yuk xati raqami')),
                ('shipment_date', models.DateField(verbose_name='Yuk chiqarish sanasi')),
                ('destination', models.CharField(max_length=200, verbose_name='Manzil')),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Haydovchi ismi')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mashina raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Yuklashga tayyor'), ('shipped', 'Yuklab jo‘natildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='shipments/files/', verbose_name='Biriktirilgan fayl (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('42-44', '42-44'), ('46-48', '46-48'), ('50-52', '50-52'), ('54-56', '54-56'), ('58-60', '58-60'), ('62-64', '62-64'), ('66-68', '66-68'), ('70-72', '70-72')], default='oversize', max_length=20, verbose_name='O‘lchami')),
                ('quantity', models.PositiveIntegerField(verbose_name='Yuk miqdori')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('karopka', 'Karopka')], default='dona', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('package_type', models.CharField(choices=[('box', 'Karopka'), ('bag', 'Xalta'), ('packet', 'Paket'), ('pallet', 'Pallet'), ('other', 'Boshqa')], default='box', max_length=20, verbose_name='Qadoq turi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.order', verbose_name='Buyurtma')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plm.shipmentinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Stitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Boshlanmagan'), ('in_progress', 'Davom etmoqda'), ('done', 'Tugallangan')], default='pending', max_length=20)),
                ('date', models.DateField(verbose_name='Kunlik tikim sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ordersize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitchings', to='plm.ordersize')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qilingan ish soni')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_works', to='plm.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_works', to='plm.order')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plm.productionline')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.worktype')),
            ],
        ),
    ]
