# Generated by Django 5.1.1 on 2025-09-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artikul')),
                ('mijoz', models.CharField(max_length=200, verbose_name='Mijoz')),
                ('ish_soni', models.PositiveIntegerField(default=0, verbose_name='Ish soni')),
                ('bajarilgan', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bajarilgan')),
                ('kesim', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kesim soni')),
                ('dazmol', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Dazmol soni')),
                ('pechat', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Pechat soni')),
                ('sifat_nazorati', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sifat nazorati soni')),
                ('tasnif', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tasnif soni')),
                ('qadoq', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qadoq soni')),
                ('tikim', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tikim soni')),
                ('model_picture', models.ImageField(blank=True, null=True, upload_to='models/', verbose_name='Model rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
        ),
    ]
