# Generated by Django 5.1.1 on 2025-09-16 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Buyurtma nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Umumiy son')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ish turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (so‘m/dona)')),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='dazmol',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dazmol soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='kesim',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kesim soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pechat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pechat soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='qadoq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qadoq soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sifat_nazorati',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sifat nazorati soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tasnif',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tasnif soni'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tikim',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tikim soni'),
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Patok nomi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plm.order')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plm.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qilingan ish soni')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_works', to='plm.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_works', to='plm.order')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.worktype')),
            ],
        ),
    ]
