# Generated by Django 5.1.1 on 2025-09-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0002_order_worktype_alter_productmodel_dazmol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='order',
        ),
        migrations.AddField(
            model_name='hourlywork',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plm.productionline'),
        ),
        migrations.AddField(
            model_name='order',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plm.productionline', verbose_name='Patok'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ism familiya'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdori (dona)'),
        ),
    ]
