# Generated by Django 5.1.1 on 2025-10-31 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0002_alter_inspection_ordersize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='O‘zgarish nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('version', models.CharField(max_length=50, verbose_name='Versiya raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
