# Generated by Django 5.1.1 on 2025-09-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0003_remove_productionline_order_hourlywork_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='line',
            field=models.ForeignKey(blank=True, default='Tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plm.productionline', verbose_name='Patok'),
        ),
    ]
