# Generated by Django 5.1.1 on 2025-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0003_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
    ]
