# Generated by Django 5.1.1 on 2025-09-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0004_alter_order_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='line',
        ),
        migrations.AddField(
            model_name='order',
            name='artikul',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Artikuli'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuklanish vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='model_picture',
            field=models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Model rasmi'),
        ),
        migrations.AddField(
            model_name='order',
            name='rangi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rangi'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
