# Generated by Django 5.1.1 on 2025-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0005_remove_order_line_order_artikul_order_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz nomi'),
        ),
    ]
