# Generated by Django 5.1.1 on 2025-09-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0006_remove_order_name_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Tikilayotgan model nomi')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_norm', models.PositiveIntegerField(verbose_name='Kunlik norma (dona)')),
                ('hourly_norm', models.PositiveIntegerField(verbose_name='Soatlik norma (dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.productionline')),
            ],
        ),
    ]
