# Generated by Django 5.1.1 on 2025-09-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0007_modelassigned_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelassigned',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.order', verbose_name='Buyurtma (Artikul)'),
        ),
    ]
