# Generated by Django 5.1.1 on 2025-09-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0008_alter_modelassigned_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=200, verbose_name='Mato nomi')),
                ('measure', models.CharField(choices=[('kg', 'Kilogram'), ('m', 'Metr')], max_length=50, verbose_name='O‘lchov birligi')),
                ('gramaj', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gramaj')),
                ('arrival_date', models.DateField(verbose_name='Qachon kelganligi')),
                ('factory_name', models.CharField(max_length=200, verbose_name='Qaysi fabrikadan kelganligi')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_arrival', to='plm.order', verbose_name='Qaysi buyurtma uchun')),
            ],
        ),
    ]
