# Generated by Django 5.1.1 on 2025-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0009_fabricarrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricarrival',
            name='measure',
        ),
        migrations.AddField(
            model_name='fabricarrival',
            name='measure_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('m', 'Metr')], max_length=10, null=True, verbose_name='O‘lchov birligi'),
        ),
        migrations.AddField(
            model_name='fabricarrival',
            name='measure_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdori'),
        ),
    ]
