# Generated by Django 5.1.1 on 2025-09-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0010_remove_fabricarrival_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Aksessuar nomi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soni')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('metr', 'Metr'), ('pachka', 'Pachka'), ('paket', 'Paket'), ('quti', 'Quti'), ('litr', 'Litr')], max_length=20, verbose_name='Birligi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
    ]
