# Generated by Django 5.1.1 on 2025-09-27 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0011_accessory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('metr', 'Metr'), ('pachka', 'Pachka'), ('paket', 'Paket'), ('quti', 'Quti'), ('litr', 'Litr')], default='dona', max_length=20, verbose_name='Birligi'),
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastal_soni', models.PositiveIntegerField(verbose_name='Pastal soni')),
                ('pastal_olchami', models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70')], max_length=20, verbose_name='Pastal o‘lchami')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuttings', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
    ]
