# Generated by Django 5.1.1 on 2025-09-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0012_alter_accessory_unit_cutting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='pastal_olchami',
            field=models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70')], default='oversize', max_length=20, verbose_name='Pastal o‘lchami'),
        ),
    ]
