# Generated by Django 5.1.1 on 2025-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0013_alter_cutting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
