# Generated by Django 5.1.1 on 2025-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0015_fabricarrival_created_at_fabricarrival_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricarrival',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Qachon kelganligi'),
        ),
    ]
