# Generated by Django 5.1.1 on 2025-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0016_alter_fabricarrival_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricarrival',
            name='gramaj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gramaj'),
        ),
        migrations.AlterField(
            model_name='fabricarrival',
            name='measure_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('m', 'Metr')], default='kg', max_length=10, null=True, verbose_name='O‘lchov birligi'),
        ),
    ]
