# Generated by Django 5.1.1 on 2025-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0018_printing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='daily_work_date',
            field=models.DateField(verbose_name='Kunlik bosilgan pechat'),
        ),
    ]
