# Generated by Django 5.1.1 on 2025-10-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0019_alter_printing_daily_work_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='pastal_olchami',
            field=models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('42-44', '42-44'), ('46-48', '46-48'), ('50-52', '50-52'), ('54-56', '54-56'), ('58-60', '58-60'), ('62-64', '62-64'), ('66-68', '66-68'), ('70-72', '70-72')], default='oversize', max_length=20, verbose_name='Pastal o‘lchami'),
        ),
        migrations.CreateModel(
            name='OrderSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('size', models.CharField(choices=[('oversize', 'Oversize'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('11XL', '11XL'), ('12XL', '12XL'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('42-44', '42-44'), ('46-48', '46-48'), ('50-52', '50-52'), ('54-56', '54-56'), ('58-60', '58-60'), ('62-64', '62-64'), ('66-68', '66-68'), ('70-72', '70-72')], default='oversize', max_length=20, verbose_name='O‘lchami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersize', to='plm.order', verbose_name='Buyurtma')),
            ],
        ),
    ]
