# Generated by Django 5.1.1 on 2025-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0020_alter_cutting_pastal_olchami_ordersize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
