# Generated by Django 5.1.1 on 2025-10-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0021_remove_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name='Kunlik tikim sanasi')),
                ('ordersize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitchings', to='plm.ordersize')),
            ],
        ),
    ]
