# Generated by Django 5.1.1 on 2025-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0022_stitching'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stitching',
            name='status',
            field=models.CharField(choices=[('pending', 'Boshlanmagan'), ('in_progress', 'Davom etmoqda'), ('done', 'Tugallangan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stitching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
