# Generated by Django 5.1.1 on 2025-10-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0024_ironing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checked', models.PositiveIntegerField(help_text='Umumiy tekshirilgan mahsulotlar soni')),
                ('passed_quantity', models.PositiveIntegerField(default=0, help_text='Sifatdan o‘tgan mahsulotlar soni')),
                ('failed_quantity', models.PositiveIntegerField(default=0, help_text='Sifatdan o‘tmagan mahsulotlar soni')),
                ('defect_notes', models.TextField(blank=True, help_text='Nuqson haqida qisqacha izoh (agar bo‘lsa)')),
                ('inspected_date', models.DateField(verbose_name='Kunlik Sifat nazorat ishi sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='plm.order')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspected_date'],
            },
        ),
    ]
