# Generated by Django 5.1.1 on 2025-10-06 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0025_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(choices=[('karopka', 'Karopka'), ('paket', 'Paket'), ('xalta', 'Xalta')], default='karopka', max_length=20, verbose_name='Qadoq turi')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Qadoqlangan mahsulot soni')),
                ('box_quantity', models.PositiveIntegerField(verbose_name='Yopilgan karopkalar soni')),
                ('packed_date', models.DateField(verbose_name='Qadoqlangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='plm.order')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
                'ordering': ['-packed_date'],
            },
        ),
    ]
