# Generated by Django 5.1.1 on 2025-10-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0026_packing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(verbose_name='Yuk chiqarish sanasi')),
                ('destination', models.CharField(max_length=200, verbose_name='Manzil')),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mashina raqami')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Haydovchi ismi')),
                ('package_type', models.CharField(choices=[('box', 'Karopka'), ('bag', 'Xalta'), ('packet', 'Paket'), ('pallet', 'Pallet'), ('other', 'Boshqa')], default='box', max_length=20, verbose_name='Qadoq turi')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='Yuk miqdori (dona)')),
                ('box_quantity', models.PositiveIntegerField(default=0, verbose_name='Karopkalar soni')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Yuklashga tayyor'), ('shipped', 'Yuklab jo‘natildi'), ('delivered', 'Yetkazildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='shipments/files/', verbose_name='Biriktirilgan fayl (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='plm.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Yuklama',
                'verbose_name_plural': 'Yuklamalar',
                'ordering': ['-shipment_date'],
            },
        ),
    ]
