# Generated by Django 5.1.1 on 2025-10-18 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0027_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Yuklashga tayyor'), ('shipped', 'Yuklab jo‘natildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='ShipmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Yuk xati raqami')),
                ('shipment_date', models.DateField(verbose_name='Yuk chiqarish sanasi')),
                ('destination', models.CharField(max_length=200, verbose_name='Manzil')),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Haydovchi ismi')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mashina raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Yuklashga tayyor'), ('shipped', 'Yuklab jo‘natildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='shipments/files/', verbose_name='Biriktirilgan fayl (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Yuk miqdori')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('karopka', 'Karopka')], default='dona', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('package_type', models.CharField(choices=[('box', 'Karopka'), ('bag', 'Xalta'), ('packet', 'Paket'), ('pallet', 'Pallet'), ('other', 'Boshqa')], default='box', max_length=20, verbose_name='Qadoq turi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plm.order', verbose_name='Buyurtma')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plm.shipmentinvoice')),
            ],
        ),
    ]
